create table foo
(
    id   bigint generated by default as identity primary key,
    name varchar not null
);

create table bar
(
    id     bigint generated by default as identity primary key,
    name   varchar not null,
    foo_id bigint  not null
        constraint bar_foo_id_fk
            references foo (id)
            on update cascade on delete cascade
);
